baseURL               = "http://web3.d1dns.com/"
languageCode          = "zh-CN"
title                 = "Web3 导航站 | 币圈导航 | 区块链导航 - D1导航网"
kewords               = "Web3 导航站 | 币圈导航 | 区块链导航 - D1导航网"
description           = "Web3 导航站 | 币圈导航 | 区块链导航 - D1导航网"
theme                 = "Navigation"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录
googleAnalytics       = 'G-QXXPENV3WP'


[params]
    author        = "D1"
    description   = "Web3 网址导航"
    upload        = ""  					# 左侧导航栏的"网站提交"
    about         = "/about"					# 左侧导航栏的"关于导航"页面(./about)
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "Web3 导航"					# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = true						# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = ''			# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''       		        # 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = 'pub-5039124460067822'	# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg2.png"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'Copyright © 2002-{year} D1 Web3 导航 , All rights reserved.'
